superRareItems = {
    2577: ["Ranger boots", 1, 1, ItemEmojis.MediumClues.rangerBoots],
    2581: ["Robin hood hat", 1, 1, ItemEmojis.HardClues.robinHoodHat],
    19994: ["Ranger gloves", 1, 1, ItemEmojis.EliteClues.rangerGloves],
    23249: ["Rangers' tights ", 1, 1, ItemEmojis.EliteClues.rangersTights],
    12596: ["Ranger's tunic", 1, 1, ItemEmojis.EliteClues.rangersTunic],
    6916: ["Infinity top", 1, 1, ItemEmojis.Infinity.infinityTop],
    6924: ["Infinity bottoms", 1, 1, ItemEmojis.Infinity.infinityBottoms],
    6922: ["Infinity boots", 1, 1, ItemEmojis.Infinity.infinityBoots],
    6922: ["Infinity gloves", 1, 1, ItemEmojis.Infinity.infinityGloves],
    6918: ["Infinity hat", 1, 1, ItemEmojis.Infinity.infinityHat],
    11802: ["Armadyl godsword", 1, 1, ItemEmojis.Armadyl.armadylGodsword],
    11806: ["Saradomin godsword", 1, 1, ItemEmojis.Saradomin.saradominGodsword],
    11808: ["Zamorak godsword", 1, 1, ItemEmojis.Zamorak.zamorakGodsword],
    11804: ["Bandos godsword", 1, 1, ItemEmojis.Bandos.bandosGodsword],
    11826: ["Armadyl helmet", 1, 1, ItemEmojis.Armadyl.armadylHelm],
    11828: ["Armadyl chestplate", 1, 1, ItemEmojis.Armadyl.armadylChestplate],
    11830: ["Armadyl chainskirt", 1, 1, ItemEmojis.Armadyl.armadylChainskirt],
    11832: ["Bandos chestplate", 1, 1, ItemEmojis.Bandos.bandosChestplate],
    11834: ["Bandos tassets", 1, 1, ItemEmojis.Bandos.bandosTassets],
    11836: ["Bandos boots", 1, 1, ItemEmojis.Bandos.bandosBoots],
    11838: ["Saradomin sword", 1, 1, ItemEmojis.Saradomin.saradominSword],
    11824: ["Zamorakian spear", 1, 1, ItemEmojis.Zamorak.zamorakianSpear],
    12902: ["Toxic staff of the dead", 1, 1, ItemEmojis.Zamorak.toxicStaff],
    13235: ["Eternal boots", 1, 1, ItemEmojis.CerberusItems.eternalBoots],
    13237: ["Pegasian boots", 1, 1, ItemEmojis.CerberusItems.pegasianBoots],
    13239: ["Primordial boots", 1, 1, ItemEmojis.CerberusItems.primordialBoots],
    19544: ["Tormented bracelet", 1, 1, ItemEmojis.Jewelry.tormentedBracelet],
    19547: ["Necklace of anguish", 1, 1, ItemEmojis.Jewelry.necklaceOfAnguish],
    19550: ["Ring of suffering", 1, 1, ItemEmojis.Jewelry.ringOfSuffering],
    19553: ["Amulet of torture", 1, 1, ItemEmojis.Jewelry.amuletOfTorture],
    21018: ["Ancestral hat", 1, 1, ItemEmojis.RaidsItems.ancestralHat],
    21021: ["Ancestral robe bottom", 1, 1, ItemEmojis.RaidsItems.ancestralRobeBottom],
    21024: ["Ancestral rbe top", 1, 1, ItemEmojis.RaidsItems.ancestralRobeTop],
    13652: ["Dragon claws", 1, 1, ItemEmojis.RaidsItems.dragonClaws],
    21006: ["Kodai wand", 1, 1, ItemEmojis.RaidsItems.kodaiWand],
    21003: ["Elder maul", 1, 1, ItemEmojis.RaidsItems.elderMaul]
}

rareItems = {
    4151: ["Abyssal whip", 1, 1, ItemEmojis.SlayerItems.abyssalWhip],
    6585: ["Amulet of fury", 1, 1, ItemEmojis.Jewelry.amuletOfFury],
    6571: ["Uncut onyx", 1, 1, ItemEmojis.RawMaterials.uncutOnyx],
    11235: ["Dark bow", 1, 1, ItemEmojis.SlayerItems.darkBow],
    12929: ["Serpentine helm", 1, 1, ItemEmojis.ZulrahItems.serpentineHelm]
}

uncommonItems = {
    1187: ["Dragon sq shield", 1, 1, ItemEmojis.DragonItems.dragonSqShield],
    4087: ["Dragon platelegs", 1, 1, ItemEmojis.DragonItems.dragonPlatelegs],
    3140: ["Dragon chainbody", 1, 1, ItemEmojis.DragonItems.dragonChainbody],
    4585: ["Dragon plateskirt", 1, 1, ItemEmojis.DragonItems.dragonPlateskirt],
    11840: ["Dragon boots", 1, 1, ItemEmojis.DragonItems.dragonBoots],
    4708: ["Ahrim's hood", 1, 1, ItemEmojis.Barrows.ahrimsHood],
    4710: ["Ahrim's staff", 1, 1, ItemEmojis.Barrows.ahrimsStaff],
    4712: ["Ahrim's robetop", 1, 1, ItemEmojis.Barrows.ahrimsRobetop],
    4714: ["Ahrim' robeskirt", 1, 1, ItemEmojis.Barrows.ahrimsRobeskirt],
    4716: ["Dharok's helm", 1, 1, ItemEmojis.Barrows.dharoksHelm],
    4718: ["Dharok's greataxe", 1, 1, ItemEmojis.Barrows.dharoksGreataxe],
    4720: ["Dharok's platelegs", 1, 1, ItemEmojis.Barrows.dharoksPlatelegs],
    4722: ["Dharok's platebody", 1, 1, ItemEmojis.Barrows.dharoksPlatebody],
    4724: ["Guthan's helm", 1, 1, ItemEmojis.Barrows.guthansHelm],
    4726: ["Guthan's spear", 1, 1, ItemEmojis.Barrows.guthansWarpear],
    4728: ["Guthan's platebody", 1, 1, ItemEmojis.Barrows.guthansPlatebody],
    4730: ["Guthan's chainskirt", 1, 1, ItemEmojis.Barrows.guthansChainskirt],
    4732: ["Karil's coif", 1, 1, ItemEmojis.Barrows.karilsCoif],
    4734: ["Karil's crossbow", 1, 1, ItemEmojis.Barrows.karilsCrossbow],
    4736: ["Karil's leathertop", 1, 1, ItemEmojis.Barrows.karilsLeathertop],
    4738: ["Karil's leatherskirt", 1, 1, ItemEmojis.Barrows.karilsLeatherskirt],
    4745: ["Torag's helm", 1, 1, ItemEmojis.Barrows.toragsHelm],
    4747: ["Torag's hammers", 1, 1, ItemEmojis.Barrows.toragsHammers],
    4749: ["Torag's platebody", 1, 1, ItemEmojis.Barrows.toragsPlatebody],
    4751: ["Torag's platelegs", 1, 1, ItemEmojis.Barrows.toragsPlatelegs],
    4753: ["Verac's helm", 1, 1, ItemEmojis.Barrows.veracsHelm],
    4755: ["Verac's flail", 1, 1, ItemEmojis.Barrows.veracsFlail],
    4757: ["Verac's brassard", 1, 1, ItemEmojis.Barrows.veracsBrassard],
    4759: ["Verac's plateskirt", 1, 1, ItemEmojis.Barrows.veracsPlateskirt]
}

commonItems = {
    385: ["Shark", 1, 16, ItemEmojis.Food.shark],
    391: ["Manta ray", 1, 16, ItemEmojis.Food.mantaRay],
    7946: ["Monkfish", 1, 16, ItemEmojis.Food.monkFish],
    13441: ["Anglerfish", 1, 16, ItemEmojis.Food.anglerFish],
    861: ["Magic shortbow", 1, 1, ItemEmojis.RangedWeapons.magicShortbow],
    1079: ["Rune platelegs", 1, 1, ItemEmojis.RuneItems.runePlatelegs],
    1093: ["Rune plateskirt", 1, 1, ItemEmojis.RuneItems.runePlateskirt],
    1163: ["Rune full helm", 1, 1, ItemEmojis.RuneItems.runeFullHelm],
    1333: ["Rune scimitar", 1, 1, ItemEmojis.RuneItems.runeScimitar],
    1127: ["Rune platebody", 1, 1, ItemEmojis.RuneItems.runePlatebody],
    1305: ["Dragon longsword", 1, 1, ItemEmojis.DragonItems.dragonLongsword],
    1377: ["Dragon battleaxe", 1, 1, ItemEmojis.DragonItems.dragonBattleaxe],
    5698: ["Dragon dagger(p++)", 1, 1, ItemEmojis.DragonItems.dragonDagger],
    1434: ["Dragon mace", 1, 1, ItemEmojis.DragonItems.dragonMace],
    4587: ["Dragon scimitar", 1, 1, ItemEmojis.DragonItems.dragonScimitar],
    4153: ["Granite maul", 1, 1, ItemEmojis.SlayerItems.graniteMaul],
    4089: ["Mystic hat", 1, 1, ItemEmojis.MysticArmor.mysticHat],
    4091: ["Mystic robe top", 1, 1, ItemEmojis.MysticArmor.mysticRobeTop],
    4093: ["Mystic robe bottom", 1, 1, ItemEmojis.MysticArmor.mysticRobeBottom],
    2503: ["Black d'hide body", 1, 1, ItemEmojis.DragonhideArmor.blackDhideBody],
    2497: ["Black d'hide chaps", 1, 1, ItemEmojis.DragonhideArmor.blackDhideChaps],
    2491: ["Black d'hide vamb", 1, 1, ItemEmojis.DragonhideArmor.blackDhideVamb],
    1712: ["Amulet of glory(4)", 1, 1, ItemEmojis.Jewelry.amuletOfGlory],
    2434: ["Prayer potion(4)", 2, 6, ItemEmojis.Potions.prayer],
    3024: ["Super restore(4)", 2, 6, ItemEmojis.Potions.superRestore],
    6685: ["Saradomin brew(4)", 2, 6, ItemEmojis.Potions.saradominBrew],
    2440: ["Super strength(4)", 1, 2, ItemEmojis.Potions.superStrength],
    2442: ["Super defence(4)", 1, 2, ItemEmojis.Potions.superDefence],
    2436: ["Super attack(4)", 1, 2, ItemEmojis.Potions.superAttack],
    12695: ["Super combat potion(4)", 1, 2, ItemEmojis.Potions.superCombat],
    2444: ["Ranging potion(4)", 1, 2, ItemEmojis.Potions.ranging]
}